// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgLc1uttpdNQYBVL7RXPPBGDgQZEYi1E',
    appId: '1:484321957016:web:5dcff960d29d7b06542ced',
    messagingSenderId: '484321957016',
    projectId: 'studentside-12e0e',
    authDomain: 'studentside-12e0e.firebaseapp.com',
    storageBucket: 'studentside-12e0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4kL0TVljBLHjGQHswY5l4zCv4F4XheXY',
    appId: '1:484321957016:android:168c50f0e3a57ad8542ced',
    messagingSenderId: '484321957016',
    projectId: 'studentside-12e0e',
    storageBucket: 'studentside-12e0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTdOsqAxCLHEbVKTE5hsvDkMyRzq3tuv0',
    appId: '1:484321957016:ios:69e965e40bdb06d6542ced',
    messagingSenderId: '484321957016',
    projectId: 'studentside-12e0e',
    storageBucket: 'studentside-12e0e.appspot.com',
    iosBundleId: 'com.example.assignmentStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTdOsqAxCLHEbVKTE5hsvDkMyRzq3tuv0',
    appId: '1:484321957016:ios:69e965e40bdb06d6542ced',
    messagingSenderId: '484321957016',
    projectId: 'studentside-12e0e',
    storageBucket: 'studentside-12e0e.appspot.com',
    iosBundleId: 'com.example.assignmentStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYgD3zzmvjbAmRpAPiDTWD0T_Bm_4O4Fg',
    appId: '1:484321957016:web:2ddb54e0394ecd1c542ced',
    messagingSenderId: '484321957016',
    projectId: 'studentside-12e0e',
    authDomain: 'studentside-12e0e.firebaseapp.com',
    storageBucket: 'studentside-12e0e.appspot.com',
  );

}